version: "3.7"
services:
  nginx:
    build:
      context: ./nginx
      args:
        DOMAIN: ${DOMAIN}
        EMAIL: ${EMAIL}
        FASTAPI: web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: [ "/entrypoint.sh" ]
    command: uvicorn start:app --host 0.0.0.0 --port 5000
    depends_on:
      - redis
      - db
    volumes: ['.:/app']
    environment:
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      CELERY_RESULT_BACKEND: redis://:${REDIS_PASSWORD}@redis:6379/0
      CACHE_REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
    env_file:
      - .env
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A services.celery worker --loglevel INFO -E
    depends_on:
      - redis
      - db
    volumes: ['.:/app']
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      CELERY_RESULT_BACKEND: redis://:${REDIS_PASSWORD}@redis:6379/0
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A services.celery beat
    depends_on:
      - redis
    volumes: ['.:/app']
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      CELERY_RESULT_BACKEND: redis://:${REDIS_PASSWORD}@redis:6379/0
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    command: celery -A services.celery flower
    environment:
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      CELERY_RESULT_BACKEND: redis://:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      - redis
      - worker
    volumes: ['.:/app']
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DATABASE
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
