"""Set up entity to track mkusd price

Revision ID: 52b9e94cc4c9
Revises: a361f5bb7044
Create Date: 2023-09-29 20:18:11.877274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b9e94cc4c9'
down_revision: Union[str, None] = 'a361f5bb7044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mkusd_price',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], name=op.f('fk__mkusd_price__chain_id__chains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__mkusd_price'))
    )
    op.create_index('idx_collaterals__chain_id__timestamp', 'mkusd_price', ['chain_id', 'timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_collaterals__chain_id__timestamp', table_name='mkusd_price')
    op.drop_table('mkusd_price')
    # ### end Alembic commands ###
