"""Store chain_id with liquidations and redemptions

Revision ID: 51a796697c57
Revises: 52b9e94cc4c9
Create Date: 2023-10-21 23:15:59.802204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a796697c57'
down_revision: Union[str, None] = '52b9e94cc4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liquidations', sa.Column('chain_id', sa.BigInteger(), nullable=False, server_default='1'))
    op.drop_index('idx_liquidations__liquidator_id__block_timestamp', table_name='liquidations')
    op.create_index('idx_liquidations__chain_id__liquidator_id__block_timestamp', 'liquidations', ['chain_id', 'liquidator_id', 'block_timestamp'], unique=True)
    op.create_foreign_key(op.f('fk__liquidations__chain_id__chains'), 'liquidations', 'chains', ['chain_id'], ['id'])
    op.add_column('redemptions', sa.Column('chain_id', sa.BigInteger(), nullable=False, server_default='1'))
    op.drop_index('idx_redemptions__redeemer_id__block_timestamp', table_name='redemptions')
    op.create_index('idx_redemptions__chain_id__redeemer_id__block_timestamp', 'redemptions', ['chain_id', 'redeemer_id', 'block_timestamp'], unique=True)
    op.create_foreign_key(op.f('fk__redemptions__chain_id__chains'), 'redemptions', 'chains', ['chain_id'], ['id'])

    op.alter_column('liquidations', 'chain_id', server_default=None)
    op.alter_column('redemptions', 'chain_id', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__redemptions__chain_id__chains'), 'redemptions', type_='foreignkey')
    op.drop_index('idx_redemptions__chain_id__redeemer_id__block_timestamp', table_name='redemptions')
    op.create_index('idx_redemptions__redeemer_id__block_timestamp', 'redemptions', ['redeemer_id', 'block_timestamp'], unique=False)
    op.drop_column('redemptions', 'chain_id')
    op.drop_constraint(op.f('fk__liquidations__chain_id__chains'), 'liquidations', type_='foreignkey')
    op.drop_index('idx_liquidations__chain_id__liquidator_id__block_timestamp', table_name='liquidations')
    op.create_index('idx_liquidations__liquidator_id__block_timestamp', 'liquidations', ['liquidator_id', 'block_timestamp'], unique=False)
    op.drop_column('liquidations', 'chain_id')
    # ### end Alembic commands ###
