"""Add tables and update user for weight storage

Revision ID: c7061fe6c293
Revises: a0382c9de0f2
Create Date: 2023-12-26 12:09:40.645623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7061fe6c293'
down_revision: Union[str, None] = 'a0382c9de0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('total_weekly_weights',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('unlock', sa.Numeric(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], name=op.f('fk__total_weekly_weights__chain_id__chains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__total_weekly_weights'))
    )
    op.create_index('idx_total_weekly_weights__week__chain_id', 'total_weekly_weights', ['week', 'chain_id'], unique=True)
    op.create_table('user_weekly_weights',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('unlock', sa.Numeric(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], name=op.f('fk__user_weekly_weights__chain_id__chains')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__user_weekly_weights__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_weekly_weights'))
    )
    op.create_index('idx_user_weekly_weights__week__chain_id__user_id', 'user_weekly_weights', ['week', 'chain_id', 'user_id'], unique=True)
    op.add_column('users', sa.Column('latest_fee', sa.Numeric(), nullable=True))
    op.add_column('users', sa.Column('frozen_balance', sa.Numeric(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight')
    op.drop_column('users', 'frozen_balance')
    op.drop_column('users', 'latest_fee')
    op.drop_index('idx_user_weekly_weights__week__chain_id__user_id', table_name='user_weekly_weights')
    op.drop_table('user_weekly_weights')
    op.drop_index('idx_total_weekly_weights__week__chain_id', table_name='total_weekly_weights')
    op.drop_table('total_weekly_weights')
    # ### end Alembic commands ###
