"""Add table for zap stakes

Revision ID: a8ef5ffc4c0a
Revises: c7061fe6c293
Create Date: 2023-12-27 07:13:19.059227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ef5ffc4c0a'
down_revision: Union[str, None] = 'c7061fe6c293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zap_stakes',
    sa.Column('collateral_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('block_number', sa.Numeric(), nullable=True),
    sa.Column('block_timestamp', sa.Numeric(), nullable=True),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['collateral_id'], ['collaterals.id'], name=op.f('fk__zap_stakes__collateral_id__collaterals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__zap_stakes'))
    )
    op.create_index('idx_zap_stakes__collateral_id__index__block_timestamp', 'zap_stakes', ['collateral_id', 'index', 'block_timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_zap_stakes__collateral_id__index__block_timestamp', table_name='zap_stakes')
    op.drop_table('zap_stakes')
    # ### end Alembic commands ###
