"""Add tables for boost data

Revision ID: a0382c9de0f2
Revises: bd9fd5b56cc2
Create Date: 2023-12-25 15:03:25.892667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0382c9de0f2'
down_revision: Union[str, None] = 'bd9fd5b56cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_claims',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('caller_id', sa.String(), nullable=True),
    sa.Column('receiver_id', sa.String(), nullable=True),
    sa.Column('delegate_id', sa.String(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('total_claimed', sa.Numeric(), nullable=True),
    sa.Column('total_claimed_boosted', sa.Numeric(), nullable=True),
    sa.Column('delegate_remaining_eligible', sa.Numeric(), nullable=True),
    sa.Column('max_fee', sa.Numeric(), nullable=True),
    sa.Column('fee_generated', sa.Numeric(), nullable=True),
    sa.Column('fee_applied', sa.Numeric(), nullable=True),
    sa.Column('block_number', sa.Numeric(), nullable=True),
    sa.Column('block_timestamp', sa.Numeric(), nullable=True),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['caller_id'], ['users.id'], name=op.f('fk__batch_claims__caller_id__users')),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], name=op.f('fk__batch_claims__chain_id__chains')),
    sa.ForeignKeyConstraint(['delegate_id'], ['users.id'], name=op.f('fk__batch_claims__delegate_id__users')),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('fk__batch_claims__receiver_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__batch_claims'))
    )
    op.create_index('idx_batch_claims__week__chain_id__caller_id__delegate_id__index', 'batch_claims', ['week', 'chain_id', 'caller_id', 'delegate_id', 'index'], unique=True)
    op.create_table('weekly_boost',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('boost', sa.Numeric(), nullable=True),
    sa.Column('pct', sa.Numeric(), nullable=True),
    sa.Column('last_applied_fee', sa.Numeric(), nullable=True),
    sa.Column('non_locking_fee', sa.Numeric(), nullable=True),
    sa.Column('boost_delegation', sa.Boolean(), nullable=True),
    sa.Column('boost_delegation_users', sa.Numeric(), nullable=True),
    sa.Column('eligible_for', sa.Numeric(), nullable=True),
    sa.Column('total_claimed', sa.Numeric(), nullable=True),
    sa.Column('self_claimed', sa.Numeric(), nullable=True),
    sa.Column('other_claimed', sa.Numeric(), nullable=True),
    sa.Column('accrued_fees', sa.Numeric(), nullable=True),
    sa.Column('time_to_depletion', sa.Numeric(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], name=op.f('fk__weekly_boost__chain_id__chains')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__weekly_boost__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__weekly_boost'))
    )
    op.create_index('idx_weekly_boost__week__chain_id__user_id', 'weekly_boost', ['week', 'chain_id', 'user_id'], unique=True)
    op.create_table('weekly_emissions',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('emissions', sa.Numeric(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], name=op.f('fk__weekly_emissions__chain_id__chains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__weekly_emissions'))
    )
    op.create_index('idx_weekly_emissions__week__chain_id', 'weekly_emissions', ['week', 'chain_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weekly_emissions__week__chain_id', table_name='weekly_emissions')
    op.drop_table('weekly_emissions')
    op.drop_index('idx_weekly_boost__week__chain_id__user_id', table_name='weekly_boost')
    op.drop_table('weekly_boost')
    op.drop_index('idx_batch_claims__week__chain_id__caller_id__delegate_id__index', table_name='batch_claims')
    op.drop_table('batch_claims')
    # ### end Alembic commands ###
