"""Store revenue snapshots

Revision ID: bf815fca9595
Revises: d29b8f513577
Create Date: 2023-11-13 19:50:53.158169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf815fca9595'
down_revision: Union[str, None] = 'd29b8f513577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prisma_revenue',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('unlock_penalty_revenue_usd', sa.Numeric(), nullable=True),
    sa.Column('borrowing_fees_revenue_usd', sa.Numeric(), nullable=True),
    sa.Column('redemption_fees_revenue_usd', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], name=op.f('fk__prisma_revenue__chain_id__chains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__prisma_revenue'))
    )
    op.create_index('idx_prisma_revenue__chain_id__timestamp', 'prisma_revenue', ['chain_id', 'timestamp'], unique=True)
    op.drop_index('idx_collaterals__chain_id__timestamp', table_name='mkusd_price')
    op.create_index('idx_mkusd_price__chain_id__timestamp', 'mkusd_price', ['chain_id', 'timestamp'], unique=True)
    op.add_column('users', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'label')
    op.drop_index('idx_mkusd_price__chain_id__timestamp', table_name='mkusd_price')
    op.create_index('idx_collaterals__chain_id__timestamp', 'mkusd_price', ['chain_id', 'timestamp'], unique=False)
    op.drop_index('idx_prisma_revenue__chain_id__timestamp', table_name='prisma_revenue')
    op.drop_table('prisma_revenue')
    # ### end Alembic commands ###
