"""Change relationship between manager and collateral

Revision ID: 980c387d42ec
Revises: 87eb4c1ec342
Create Date: 2024-02-01 22:19:03.373283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980c387d42ec'
down_revision: Union[str, None] = '87eb4c1ec342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk__collaterals__manager_id__trove_managers', 'collaterals', type_='foreignkey')
    op.drop_column('collaterals', 'manager_id')
    op.add_column('trove_managers', sa.Column('collateral_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk__trove_managers__collateral_id__collaterals'), 'trove_managers', 'collaterals', ['collateral_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__trove_managers__collateral_id__collaterals'), 'trove_managers', type_='foreignkey')
    op.drop_column('trove_managers', 'collateral_id')
    op.add_column('collaterals', sa.Column('manager_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk__collaterals__manager_id__trove_managers', 'collaterals', 'trove_managers', ['manager_id'], ['id'])
    # ### end Alembic commands ###
