"""Store proposal execution timestamp

Revision ID: 87eb4c1ec342
Revises: a8ef5ffc4c0a
Create Date: 2024-02-01 10:45:51.734005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87eb4c1ec342'
down_revision: Union[str, None] = 'a8ef5ffc4c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ownership_proposals', sa.Column('execution_timestamp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ownership_proposals', 'execution_timestamp')
    # ### end Alembic commands ###
